spring:
  application:
    name: school-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/zis_school
    username: root
    password: Himalaya@787375      # ⬅︎ move to an env‑var or secret in real deployments

  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
  #        format_sql: true           # pretty‑prints SQL in logs

  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:./uploads/
        -
  mail:
    host: smtp.gmail.com
    port: 587
    username: jhahimalaya534@gmail.com
    password: yzxttblweugcugsu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
#        SQL: DEBUG
#        type: TRACE
#      org.springframework.security: DEBUG

app:
  jwt-secret: efb4c2bcdf2ad82a8318f4985bedf1ec10a722f0822d5f5c26520e53cb65c279
  jwt-expiration-milliseconds: 604800000   # 7 days
  frontend:
    reset-base-url: http://localhost:3000/reset-password
