#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/zis_school
#    username: root
#    password: Himalaya@787375
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
##  flyway:
##    enabled: true
##    locations: classpath:db/migration
#
#server:
#  port: 8085
#
#app:
#  jwt:
#    secret: efb4c2bcdf2ad82a8318f4985bedf1ec10a722f0822d5f5c26520e53cb65c279
#    expiration-milliseconds: 86400000
